// Generated by tools/generate_saf_limits.dart; do not edit.
abstract final class SafLimits {
  static const maxDocuments = 100000;
  static const maxDepth = 64;
  static const maxRelativePathBytes = 4096;
  static const maxAggregatePathBytes = 33554432;
  static const maxNoteBytes = 2097152;
  static const maxReadBatchNotes = 128;
  static const maxReadBatchBytes = 16777216;
  static const maxConcurrentNoteReads = 4;
  static const maxScanNoteBytes = 134217728;
}
