// Generated by tools/generate_saf_limits.dart; do not edit.
internal object SafLimits {
    const val MAX_DOCUMENTS = 100000
    const val MAX_DEPTH = 64
    const val MAX_RELATIVE_PATH_BYTES = 4096
    const val MAX_AGGREGATE_PATH_BYTES = 33554432
    const val MAX_NOTE_BYTES = 2097152
    const val MAX_READ_BATCH_NOTES = 128
    const val MAX_READ_BATCH_BYTES = 16777216
    const val MAX_CONCURRENT_NOTE_READS = 4
    const val MAX_SCAN_NOTE_BYTES = 134217728
}
