// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `category`, `error_message`, `media_item`, `note_summary`, `open_gallery`, `parse_virtual_filters`, `scan_report`, `virtual_filter_key`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`

Future<void> prepareAppDataDirectory({
  required String directoryPath,
  required String vaultPath,
}) => RustLib.instance.api.crateApiPrepareAppDataDirectory(
  directoryPath: directoryPath,
  vaultPath: vaultPath,
);

Future<String?> loadVaultPath({required String directoryPath}) =>
    RustLib.instance.api.crateApiLoadVaultPath(directoryPath: directoryPath);

Future<String> saveVaultPath({
  required String directoryPath,
  required String vaultPath,
}) => RustLib.instance.api.crateApiSaveVaultPath(
  directoryPath: directoryPath,
  vaultPath: vaultPath,
);

Future<ScanReport> scan({
  required String vaultPath,
  required String indexPath,
}) => RustLib.instance.api.crateApiScan(
  vaultPath: vaultPath,
  indexPath: indexPath,
);

Future<List<Category>> listCategories({
  required String vaultPath,
  required String indexPath,
  required List<String> filters,
  required List<String> virtualFilters,
}) => RustLib.instance.api.crateApiListCategories(
  vaultPath: vaultPath,
  indexPath: indexPath,
  filters: filters,
  virtualFilters: virtualFilters,
);

Future<List<NoteSummary>> queryNotes({
  required String vaultPath,
  required String indexPath,
  required List<String> filters,
  required List<String> virtualFilters,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiQueryNotes(
  vaultPath: vaultPath,
  indexPath: indexPath,
  filters: filters,
  virtualFilters: virtualFilters,
  offset: offset,
  limit: limit,
);

Future<List<MediaItem>> queryMedia({
  required String vaultPath,
  required String indexPath,
  required List<String> filters,
  required List<String> virtualFilters,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiQueryMedia(
  vaultPath: vaultPath,
  indexPath: indexPath,
  filters: filters,
  virtualFilters: virtualFilters,
  offset: offset,
  limit: limit,
);

Future<int> warningCount({
  required String vaultPath,
  required String indexPath,
}) => RustLib.instance.api.crateApiWarningCount(
  vaultPath: vaultPath,
  indexPath: indexPath,
);

Future<Uint8List?> getThumbnail({
  required String vaultPath,
  required String indexPath,
  required String cachePath,
  required int mediaId,
  required int size,
}) => RustLib.instance.api.crateApiGetThumbnail(
  vaultPath: vaultPath,
  indexPath: indexPath,
  cachePath: cachePath,
  mediaId: mediaId,
  size: size,
);

class Category {
  final String path;
  final String displayName;
  final List<CategoryOption> options;
  final int count;

  const Category({
    required this.path,
    required this.displayName,
    required this.options,
    required this.count,
  });

  @override
  int get hashCode =>
      path.hashCode ^ displayName.hashCode ^ options.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          displayName == other.displayName &&
          options == other.options &&
          count == other.count;
}

class CategoryOption {
  final String name;
  final String fullTag;
  final int count;
  final bool disabled;
  final String? virtualFilter;

  const CategoryOption({
    required this.name,
    required this.fullTag,
    required this.count,
    required this.disabled,
    this.virtualFilter,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      fullTag.hashCode ^
      count.hashCode ^
      disabled.hashCode ^
      virtualFilter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryOption &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fullTag == other.fullTag &&
          count == other.count &&
          disabled == other.disabled &&
          virtualFilter == other.virtualFilter;
}

class MediaItem {
  final int id;
  final int noteId;
  final bool isVideo;
  final bool exists;

  const MediaItem({
    required this.id,
    required this.noteId,
    required this.isVideo,
    required this.exists,
  });

  @override
  int get hashCode =>
      id.hashCode ^ noteId.hashCode ^ isVideo.hashCode ^ exists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          noteId == other.noteId &&
          isVideo == other.isVideo &&
          exists == other.exists;
}

class NoteSummary {
  final int id;
  final String path;
  final String title;
  final int mediaCount;
  final int videoCount;
  final int? representativeMediaId;

  const NoteSummary({
    required this.id,
    required this.path,
    required this.title,
    required this.mediaCount,
    required this.videoCount,
    this.representativeMediaId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      title.hashCode ^
      mediaCount.hashCode ^
      videoCount.hashCode ^
      representativeMediaId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          title == other.title &&
          mediaCount == other.mediaCount &&
          videoCount == other.videoCount &&
          representativeMediaId == other.representativeMediaId;
}

class ScanReport {
  final int notesIndexed;
  final int warnings;

  const ScanReport({required this.notesIndexed, required this.warnings});

  @override
  int get hashCode => notesIndexed.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanReport &&
          runtimeType == other.runtimeType &&
          notesIndexed == other.notesIndexed &&
          warnings == other.warnings;
}
