// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `category`, `detail_line`, `error_message`, `media_item`, `note_detail`, `note_summary`, `open_gallery`, `parse_virtual_filters`, `scan_report`, `split_filter_modes`, `virtual_filter_key`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

Future<void> prepareAppDataDirectory({
  required String directoryPath,
  required String vaultPath,
}) => RustLib.instance.api.crateApiPrepareAppDataDirectory(
  directoryPath: directoryPath,
  vaultPath: vaultPath,
);

Future<void> prepareAppDataDirectorySaf({required String directoryPath}) =>
    RustLib.instance.api.crateApiPrepareAppDataDirectorySaf(
      directoryPath: directoryPath,
    );

Future<String?> loadVaultPath({required String directoryPath}) =>
    RustLib.instance.api.crateApiLoadVaultPath(directoryPath: directoryPath);

Future<String> saveVaultPath({
  required String directoryPath,
  required String vaultPath,
}) => RustLib.instance.api.crateApiSaveVaultPath(
  directoryPath: directoryPath,
  vaultPath: vaultPath,
);

Future<ScanReport> scan({
  required String vaultPath,
  required String indexPath,
}) => RustLib.instance.api.crateApiScan(
  vaultPath: vaultPath,
  indexPath: indexPath,
);

Future<ScanReport> scanSaf({
  required String vaultPath,
  required String indexPath,
  required List<SafNote> notes,
  required List<String> filePaths,
}) => RustLib.instance.api.crateApiScanSaf(
  vaultPath: vaultPath,
  indexPath: indexPath,
  notes: notes,
  filePaths: filePaths,
);

Future<List<Category>> listCategories({
  required String vaultPath,
  required String indexPath,
  required List<String> filters,
  required List<String> excludedFilters,
  required List<String> virtualFilters,
}) => RustLib.instance.api.crateApiListCategories(
  vaultPath: vaultPath,
  indexPath: indexPath,
  filters: filters,
  excludedFilters: excludedFilters,
  virtualFilters: virtualFilters,
);

Future<List<NoteSummary>> queryNotes({
  required String vaultPath,
  required String indexPath,
  required List<String> filters,
  required List<String> excludedFilters,
  required List<String> virtualFilters,
  required String searchQuery,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiQueryNotes(
  vaultPath: vaultPath,
  indexPath: indexPath,
  filters: filters,
  excludedFilters: excludedFilters,
  virtualFilters: virtualFilters,
  searchQuery: searchQuery,
  offset: offset,
  limit: limit,
);

Future<int> countNotes({
  required String vaultPath,
  required String indexPath,
  required List<String> filters,
  required List<String> excludedFilters,
  required List<String> virtualFilters,
  required String searchQuery,
}) => RustLib.instance.api.crateApiCountNotes(
  vaultPath: vaultPath,
  indexPath: indexPath,
  filters: filters,
  excludedFilters: excludedFilters,
  virtualFilters: virtualFilters,
  searchQuery: searchQuery,
);

Future<List<MediaItem>> queryMedia({
  required String vaultPath,
  required String indexPath,
  required List<String> filters,
  required List<String> excludedFilters,
  required List<String> virtualFilters,
  required String searchQuery,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiQueryMedia(
  vaultPath: vaultPath,
  indexPath: indexPath,
  filters: filters,
  excludedFilters: excludedFilters,
  virtualFilters: virtualFilters,
  searchQuery: searchQuery,
  offset: offset,
  limit: limit,
);

Future<int> countMedia({
  required String vaultPath,
  required String indexPath,
  required List<String> filters,
  required List<String> excludedFilters,
  required List<String> virtualFilters,
  required String searchQuery,
}) => RustLib.instance.api.crateApiCountMedia(
  vaultPath: vaultPath,
  indexPath: indexPath,
  filters: filters,
  excludedFilters: excludedFilters,
  virtualFilters: virtualFilters,
  searchQuery: searchQuery,
);

Future<NoteDetail?> getNoteDetail({
  required String vaultPath,
  required String indexPath,
  required int noteId,
}) => RustLib.instance.api.crateApiGetNoteDetail(
  vaultPath: vaultPath,
  indexPath: indexPath,
  noteId: noteId,
);

Future<NoteDetail?> getNoteDetailSaf({
  required String vaultPath,
  required String indexPath,
  required int noteId,
  required List<int> content,
}) => RustLib.instance.api.crateApiGetNoteDetailSaf(
  vaultPath: vaultPath,
  indexPath: indexPath,
  noteId: noteId,
  content: content,
);

Future<String?> getNotePath({
  required String vaultPath,
  required String indexPath,
  required int noteId,
}) => RustLib.instance.api.crateApiGetNotePath(
  vaultPath: vaultPath,
  indexPath: indexPath,
  noteId: noteId,
);

Future<String?> getMediaSourcePath({
  required String vaultPath,
  required String indexPath,
  required int mediaId,
}) => RustLib.instance.api.crateApiGetMediaSourcePath(
  vaultPath: vaultPath,
  indexPath: indexPath,
  mediaId: mediaId,
);

Future<String?> getMediaRelativePath({
  required String vaultPath,
  required String indexPath,
  required int mediaId,
}) => RustLib.instance.api.crateApiGetMediaRelativePath(
  vaultPath: vaultPath,
  indexPath: indexPath,
  mediaId: mediaId,
);

Future<int> warningCount({
  required String vaultPath,
  required String indexPath,
}) => RustLib.instance.api.crateApiWarningCount(
  vaultPath: vaultPath,
  indexPath: indexPath,
);

Future<Uint8List?> getThumbnail({
  required String vaultPath,
  required String indexPath,
  required String cachePath,
  required int mediaId,
  required int size,
}) => RustLib.instance.api.crateApiGetThumbnail(
  vaultPath: vaultPath,
  indexPath: indexPath,
  cachePath: cachePath,
  mediaId: mediaId,
  size: size,
);

Future<String?> getVideoSourcePath({
  required String vaultPath,
  required String indexPath,
  required int mediaId,
}) => RustLib.instance.api.crateApiGetVideoSourcePath(
  vaultPath: vaultPath,
  indexPath: indexPath,
  mediaId: mediaId,
);

class Category {
  final String path;
  final String displayName;
  final List<CategoryOption> options;
  final int count;

  const Category({
    required this.path,
    required this.displayName,
    required this.options,
    required this.count,
  });

  @override
  int get hashCode =>
      path.hashCode ^ displayName.hashCode ^ options.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          displayName == other.displayName &&
          options == other.options &&
          count == other.count;
}

class CategoryOption {
  final String name;
  final String fullTag;
  final int count;
  final bool disabled;
  final String? virtualFilter;

  const CategoryOption({
    required this.name,
    required this.fullTag,
    required this.count,
    required this.disabled,
    this.virtualFilter,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      fullTag.hashCode ^
      count.hashCode ^
      disabled.hashCode ^
      virtualFilter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryOption &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fullTag == other.fullTag &&
          count == other.count &&
          disabled == other.disabled &&
          virtualFilter == other.virtualFilter;
}

class DetailLine {
  final String text;
  final List<String> urls;
  final bool isBullet;
  final int indentLevel;
  final int? linkedNoteId;

  const DetailLine({
    required this.text,
    required this.urls,
    required this.isBullet,
    required this.indentLevel,
    this.linkedNoteId,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      urls.hashCode ^
      isBullet.hashCode ^
      indentLevel.hashCode ^
      linkedNoteId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DetailLine &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          urls == other.urls &&
          isBullet == other.isBullet &&
          indentLevel == other.indentLevel &&
          linkedNoteId == other.linkedNoteId;
}

class MediaItem {
  final int id;
  final int noteId;
  final bool isVideo;
  final bool exists;
  final int mediaCount;
  final int memoCount;
  final int relatedCount;

  const MediaItem({
    required this.id,
    required this.noteId,
    required this.isVideo,
    required this.exists,
    required this.mediaCount,
    required this.memoCount,
    required this.relatedCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      noteId.hashCode ^
      isVideo.hashCode ^
      exists.hashCode ^
      mediaCount.hashCode ^
      memoCount.hashCode ^
      relatedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          noteId == other.noteId &&
          isVideo == other.isVideo &&
          exists == other.exists &&
          mediaCount == other.mediaCount &&
          memoCount == other.memoCount &&
          relatedCount == other.relatedCount;
}

class NoteDetail {
  final int id;
  final String path;
  final String title;
  final String? author;
  final String? authorUrl;
  final String? url;
  final String? published;
  final String? created;
  final String? updated;
  final List<String> tags;
  final String bodyText;
  final List<DetailLine> memoLines;
  final List<DetailLine> relatedLines;
  final List<MediaItem> media;

  const NoteDetail({
    required this.id,
    required this.path,
    required this.title,
    this.author,
    this.authorUrl,
    this.url,
    this.published,
    this.created,
    this.updated,
    required this.tags,
    required this.bodyText,
    required this.memoLines,
    required this.relatedLines,
    required this.media,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      title.hashCode ^
      author.hashCode ^
      authorUrl.hashCode ^
      url.hashCode ^
      published.hashCode ^
      created.hashCode ^
      updated.hashCode ^
      tags.hashCode ^
      bodyText.hashCode ^
      memoLines.hashCode ^
      relatedLines.hashCode ^
      media.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          title == other.title &&
          author == other.author &&
          authorUrl == other.authorUrl &&
          url == other.url &&
          published == other.published &&
          created == other.created &&
          updated == other.updated &&
          tags == other.tags &&
          bodyText == other.bodyText &&
          memoLines == other.memoLines &&
          relatedLines == other.relatedLines &&
          media == other.media;
}

class NoteSummary {
  final int id;
  final String path;
  final String title;
  final int mediaCount;
  final int videoCount;
  final int memoCount;
  final int relatedCount;
  final int? representativeMediaId;

  const NoteSummary({
    required this.id,
    required this.path,
    required this.title,
    required this.mediaCount,
    required this.videoCount,
    required this.memoCount,
    required this.relatedCount,
    this.representativeMediaId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      title.hashCode ^
      mediaCount.hashCode ^
      videoCount.hashCode ^
      memoCount.hashCode ^
      relatedCount.hashCode ^
      representativeMediaId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          title == other.title &&
          mediaCount == other.mediaCount &&
          videoCount == other.videoCount &&
          memoCount == other.memoCount &&
          relatedCount == other.relatedCount &&
          representativeMediaId == other.representativeMediaId;
}

class SafNote {
  final String path;
  final PlatformInt64 modifiedNanos;
  final PlatformInt64 size;
  final Uint8List? content;

  const SafNote({
    required this.path,
    required this.modifiedNanos,
    required this.size,
    this.content,
  });

  @override
  int get hashCode =>
      path.hashCode ^ modifiedNanos.hashCode ^ size.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafNote &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          modifiedNanos == other.modifiedNanos &&
          size == other.size &&
          content == other.content;
}

class ScanReport {
  final int notesIndexed;
  final int warnings;

  const ScanReport({required this.notesIndexed, required this.warnings});

  @override
  int get hashCode => notesIndexed.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanReport &&
          runtimeType == other.runtimeType &&
          notesIndexed == other.notesIndexed &&
          warnings == other.warnings;
}
