// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 591426332;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'gallery_bridge',
        ioDirectory: '../crates/gallery-bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiCountMedia({
    required String vaultPath,
    required String indexPath,
    required List<String> filters,
    required List<String> excludedFilters,
    required List<String> virtualFilters,
    required String searchQuery,
  });

  Future<int> crateApiCountNotes({
    required String vaultPath,
    required String indexPath,
    required List<String> filters,
    required List<String> excludedFilters,
    required List<String> virtualFilters,
    required String searchQuery,
  });

  Future<String?> crateApiGetMediaRelativePath({
    required String vaultPath,
    required String indexPath,
    required int mediaId,
  });

  Future<String?> crateApiGetMediaSourcePath({
    required String vaultPath,
    required String indexPath,
    required int mediaId,
  });

  Future<NoteDetail?> crateApiGetNoteDetail({
    required String vaultPath,
    required String indexPath,
    required int noteId,
  });

  Future<NoteDetail?> crateApiGetNoteDetailSaf({
    required String vaultPath,
    required String indexPath,
    required int noteId,
    required List<int> content,
  });

  Future<String?> crateApiGetNotePath({
    required String vaultPath,
    required String indexPath,
    required int noteId,
  });

  Future<Uint8List?> crateApiGetThumbnail({
    required String vaultPath,
    required String indexPath,
    required String cachePath,
    required int mediaId,
    required int size,
  });

  Future<String?> crateApiGetVideoSourcePath({
    required String vaultPath,
    required String indexPath,
    required int mediaId,
  });

  Future<List<Category>> crateApiListCategories({
    required String vaultPath,
    required String indexPath,
    required List<String> filters,
    required List<String> excludedFilters,
    required List<String> virtualFilters,
  });

  Future<String?> crateApiLoadVaultPath({required String directoryPath});

  Future<void> crateApiPrepareAppDataDirectory({
    required String directoryPath,
    required String vaultPath,
  });

  Future<void> crateApiPrepareAppDataDirectorySaf({
    required String directoryPath,
  });

  Future<List<MediaItem>> crateApiQueryMedia({
    required String vaultPath,
    required String indexPath,
    required List<String> filters,
    required List<String> excludedFilters,
    required List<String> virtualFilters,
    required String searchQuery,
    required int offset,
    required int limit,
  });

  Future<List<NoteSummary>> crateApiQueryNotes({
    required String vaultPath,
    required String indexPath,
    required List<String> filters,
    required List<String> excludedFilters,
    required List<String> virtualFilters,
    required String searchQuery,
    required int offset,
    required int limit,
  });

  Future<String> crateApiSaveVaultPath({
    required String directoryPath,
    required String vaultPath,
  });

  Future<ScanReport> crateApiScan({
    required String vaultPath,
    required String indexPath,
  });

  Future<ScanReport> crateApiScanSaf({
    required String vaultPath,
    required String indexPath,
    required List<SafNote> notes,
    required List<String> filePaths,
  });

  Future<int> crateApiWarningCount({
    required String vaultPath,
    required String indexPath,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiCountMedia({
    required String vaultPath,
    required String indexPath,
    required List<String> filters,
    required List<String> excludedFilters,
    required List<String> virtualFilters,
    required String searchQuery,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_list_String(filters, serializer);
          sse_encode_list_String(excludedFilters, serializer);
          sse_encode_list_String(virtualFilters, serializer);
          sse_encode_String(searchQuery, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCountMediaConstMeta,
        argValues: [
          vaultPath,
          indexPath,
          filters,
          excludedFilters,
          virtualFilters,
          searchQuery,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCountMediaConstMeta => const TaskConstMeta(
    debugName: "count_media",
    argNames: [
      "vaultPath",
      "indexPath",
      "filters",
      "excludedFilters",
      "virtualFilters",
      "searchQuery",
    ],
  );

  @override
  Future<int> crateApiCountNotes({
    required String vaultPath,
    required String indexPath,
    required List<String> filters,
    required List<String> excludedFilters,
    required List<String> virtualFilters,
    required String searchQuery,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_list_String(filters, serializer);
          sse_encode_list_String(excludedFilters, serializer);
          sse_encode_list_String(virtualFilters, serializer);
          sse_encode_String(searchQuery, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCountNotesConstMeta,
        argValues: [
          vaultPath,
          indexPath,
          filters,
          excludedFilters,
          virtualFilters,
          searchQuery,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCountNotesConstMeta => const TaskConstMeta(
    debugName: "count_notes",
    argNames: [
      "vaultPath",
      "indexPath",
      "filters",
      "excludedFilters",
      "virtualFilters",
      "searchQuery",
    ],
  );

  @override
  Future<String?> crateApiGetMediaRelativePath({
    required String vaultPath,
    required String indexPath,
    required int mediaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_u_32(mediaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetMediaRelativePathConstMeta,
        argValues: [vaultPath, indexPath, mediaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetMediaRelativePathConstMeta =>
      const TaskConstMeta(
        debugName: "get_media_relative_path",
        argNames: ["vaultPath", "indexPath", "mediaId"],
      );

  @override
  Future<String?> crateApiGetMediaSourcePath({
    required String vaultPath,
    required String indexPath,
    required int mediaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_u_32(mediaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetMediaSourcePathConstMeta,
        argValues: [vaultPath, indexPath, mediaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetMediaSourcePathConstMeta => const TaskConstMeta(
    debugName: "get_media_source_path",
    argNames: ["vaultPath", "indexPath", "mediaId"],
  );

  @override
  Future<NoteDetail?> crateApiGetNoteDetail({
    required String vaultPath,
    required String indexPath,
    required int noteId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_u_32(noteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_note_detail,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetNoteDetailConstMeta,
        argValues: [vaultPath, indexPath, noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetNoteDetailConstMeta => const TaskConstMeta(
    debugName: "get_note_detail",
    argNames: ["vaultPath", "indexPath", "noteId"],
  );

  @override
  Future<NoteDetail?> crateApiGetNoteDetailSaf({
    required String vaultPath,
    required String indexPath,
    required int noteId,
    required List<int> content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_u_32(noteId, serializer);
          sse_encode_list_prim_u_8_loose(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_note_detail,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetNoteDetailSafConstMeta,
        argValues: [vaultPath, indexPath, noteId, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetNoteDetailSafConstMeta => const TaskConstMeta(
    debugName: "get_note_detail_saf",
    argNames: ["vaultPath", "indexPath", "noteId", "content"],
  );

  @override
  Future<String?> crateApiGetNotePath({
    required String vaultPath,
    required String indexPath,
    required int noteId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_u_32(noteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetNotePathConstMeta,
        argValues: [vaultPath, indexPath, noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetNotePathConstMeta => const TaskConstMeta(
    debugName: "get_note_path",
    argNames: ["vaultPath", "indexPath", "noteId"],
  );

  @override
  Future<Uint8List?> crateApiGetThumbnail({
    required String vaultPath,
    required String indexPath,
    required String cachePath,
    required int mediaId,
    required int size,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_String(cachePath, serializer);
          sse_encode_u_32(mediaId, serializer);
          sse_encode_u_32(size, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetThumbnailConstMeta,
        argValues: [vaultPath, indexPath, cachePath, mediaId, size],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetThumbnailConstMeta => const TaskConstMeta(
    debugName: "get_thumbnail",
    argNames: ["vaultPath", "indexPath", "cachePath", "mediaId", "size"],
  );

  @override
  Future<String?> crateApiGetVideoSourcePath({
    required String vaultPath,
    required String indexPath,
    required int mediaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_u_32(mediaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetVideoSourcePathConstMeta,
        argValues: [vaultPath, indexPath, mediaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetVideoSourcePathConstMeta => const TaskConstMeta(
    debugName: "get_video_source_path",
    argNames: ["vaultPath", "indexPath", "mediaId"],
  );

  @override
  Future<List<Category>> crateApiListCategories({
    required String vaultPath,
    required String indexPath,
    required List<String> filters,
    required List<String> excludedFilters,
    required List<String> virtualFilters,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_list_String(filters, serializer);
          sse_encode_list_String(excludedFilters, serializer);
          sse_encode_list_String(virtualFilters, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_category,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListCategoriesConstMeta,
        argValues: [
          vaultPath,
          indexPath,
          filters,
          excludedFilters,
          virtualFilters,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListCategoriesConstMeta => const TaskConstMeta(
    debugName: "list_categories",
    argNames: [
      "vaultPath",
      "indexPath",
      "filters",
      "excludedFilters",
      "virtualFilters",
    ],
  );

  @override
  Future<String?> crateApiLoadVaultPath({required String directoryPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(directoryPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoadVaultPathConstMeta,
        argValues: [directoryPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadVaultPathConstMeta => const TaskConstMeta(
    debugName: "load_vault_path",
    argNames: ["directoryPath"],
  );

  @override
  Future<void> crateApiPrepareAppDataDirectory({
    required String directoryPath,
    required String vaultPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(directoryPath, serializer);
          sse_encode_String(vaultPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPrepareAppDataDirectoryConstMeta,
        argValues: [directoryPath, vaultPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrepareAppDataDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_app_data_directory",
        argNames: ["directoryPath", "vaultPath"],
      );

  @override
  Future<void> crateApiPrepareAppDataDirectorySaf({
    required String directoryPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(directoryPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPrepareAppDataDirectorySafConstMeta,
        argValues: [directoryPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrepareAppDataDirectorySafConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_app_data_directory_saf",
        argNames: ["directoryPath"],
      );

  @override
  Future<List<MediaItem>> crateApiQueryMedia({
    required String vaultPath,
    required String indexPath,
    required List<String> filters,
    required List<String> excludedFilters,
    required List<String> virtualFilters,
    required String searchQuery,
    required int offset,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_list_String(filters, serializer);
          sse_encode_list_String(excludedFilters, serializer);
          sse_encode_list_String(virtualFilters, serializer);
          sse_encode_String(searchQuery, serializer);
          sse_encode_u_32(offset, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_media_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQueryMediaConstMeta,
        argValues: [
          vaultPath,
          indexPath,
          filters,
          excludedFilters,
          virtualFilters,
          searchQuery,
          offset,
          limit,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryMediaConstMeta => const TaskConstMeta(
    debugName: "query_media",
    argNames: [
      "vaultPath",
      "indexPath",
      "filters",
      "excludedFilters",
      "virtualFilters",
      "searchQuery",
      "offset",
      "limit",
    ],
  );

  @override
  Future<List<NoteSummary>> crateApiQueryNotes({
    required String vaultPath,
    required String indexPath,
    required List<String> filters,
    required List<String> excludedFilters,
    required List<String> virtualFilters,
    required String searchQuery,
    required int offset,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_list_String(filters, serializer);
          sse_encode_list_String(excludedFilters, serializer);
          sse_encode_list_String(virtualFilters, serializer);
          sse_encode_String(searchQuery, serializer);
          sse_encode_u_32(offset, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_note_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQueryNotesConstMeta,
        argValues: [
          vaultPath,
          indexPath,
          filters,
          excludedFilters,
          virtualFilters,
          searchQuery,
          offset,
          limit,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryNotesConstMeta => const TaskConstMeta(
    debugName: "query_notes",
    argNames: [
      "vaultPath",
      "indexPath",
      "filters",
      "excludedFilters",
      "virtualFilters",
      "searchQuery",
      "offset",
      "limit",
    ],
  );

  @override
  Future<String> crateApiSaveVaultPath({
    required String directoryPath,
    required String vaultPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(directoryPath, serializer);
          sse_encode_String(vaultPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveVaultPathConstMeta,
        argValues: [directoryPath, vaultPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveVaultPathConstMeta => const TaskConstMeta(
    debugName: "save_vault_path",
    argNames: ["directoryPath", "vaultPath"],
  );

  @override
  Future<ScanReport> crateApiScan({
    required String vaultPath,
    required String indexPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scan_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScanConstMeta,
        argValues: [vaultPath, indexPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanConstMeta => const TaskConstMeta(
    debugName: "scan",
    argNames: ["vaultPath", "indexPath"],
  );

  @override
  Future<ScanReport> crateApiScanSaf({
    required String vaultPath,
    required String indexPath,
    required List<SafNote> notes,
    required List<String> filePaths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          sse_encode_list_saf_note(notes, serializer);
          sse_encode_list_String(filePaths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scan_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScanSafConstMeta,
        argValues: [vaultPath, indexPath, notes, filePaths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanSafConstMeta => const TaskConstMeta(
    debugName: "scan_saf",
    argNames: ["vaultPath", "indexPath", "notes", "filePaths"],
  );

  @override
  Future<int> crateApiWarningCount({
    required String vaultPath,
    required String indexPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultPath, serializer);
          sse_encode_String(indexPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWarningCountConstMeta,
        argValues: [vaultPath, indexPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWarningCountConstMeta => const TaskConstMeta(
    debugName: "warning_count",
    argNames: ["vaultPath", "indexPath"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  NoteDetail dco_decode_box_autoadd_note_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_note_detail(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Category dco_decode_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Category(
      path: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      options: dco_decode_list_category_option(arr[2]),
      count: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  CategoryOption dco_decode_category_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CategoryOption(
      name: dco_decode_String(arr[0]),
      fullTag: dco_decode_String(arr[1]),
      count: dco_decode_u_32(arr[2]),
      disabled: dco_decode_bool(arr[3]),
      virtualFilter: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  DetailLine dco_decode_detail_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DetailLine(
      text: dco_decode_String(arr[0]),
      urls: dco_decode_list_String(arr[1]),
      isBullet: dco_decode_bool(arr[2]),
      indentLevel: dco_decode_u_8(arr[3]),
      linkedNoteId: dco_decode_opt_box_autoadd_u_32(arr[4]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Category> dco_decode_list_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_category).toList();
  }

  @protected
  List<CategoryOption> dco_decode_list_category_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_category_option).toList();
  }

  @protected
  List<DetailLine> dco_decode_list_detail_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_detail_line).toList();
  }

  @protected
  List<MediaItem> dco_decode_list_media_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_item).toList();
  }

  @protected
  List<NoteSummary> dco_decode_list_note_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_summary).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SafNote> dco_decode_list_saf_note(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_saf_note).toList();
  }

  @protected
  MediaItem dco_decode_media_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MediaItem(
      id: dco_decode_u_32(arr[0]),
      noteId: dco_decode_u_32(arr[1]),
      isVideo: dco_decode_bool(arr[2]),
      exists: dco_decode_bool(arr[3]),
      mediaCount: dco_decode_u_32(arr[4]),
      memoCount: dco_decode_u_32(arr[5]),
      relatedCount: dco_decode_u_32(arr[6]),
    );
  }

  @protected
  NoteDetail dco_decode_note_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return NoteDetail(
      id: dco_decode_u_32(arr[0]),
      path: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      author: dco_decode_opt_String(arr[3]),
      authorUrl: dco_decode_opt_String(arr[4]),
      url: dco_decode_opt_String(arr[5]),
      published: dco_decode_opt_String(arr[6]),
      created: dco_decode_opt_String(arr[7]),
      updated: dco_decode_opt_String(arr[8]),
      tags: dco_decode_list_String(arr[9]),
      bodyText: dco_decode_String(arr[10]),
      memoLines: dco_decode_list_detail_line(arr[11]),
      relatedLines: dco_decode_list_detail_line(arr[12]),
      media: dco_decode_list_media_item(arr[13]),
    );
  }

  @protected
  NoteSummary dco_decode_note_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return NoteSummary(
      id: dco_decode_u_32(arr[0]),
      path: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      mediaCount: dco_decode_u_32(arr[3]),
      videoCount: dco_decode_u_32(arr[4]),
      memoCount: dco_decode_u_32(arr[5]),
      relatedCount: dco_decode_u_32(arr[6]),
      representativeMediaId: dco_decode_opt_box_autoadd_u_32(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  NoteDetail? dco_decode_opt_box_autoadd_note_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_note_detail(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  SafNote dco_decode_saf_note(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SafNote(
      path: dco_decode_String(arr[0]),
      modifiedNanos: dco_decode_i_64(arr[1]),
      size: dco_decode_i_64(arr[2]),
      content: dco_decode_opt_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  ScanReport dco_decode_scan_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ScanReport(
      notesIndexed: dco_decode_u_32(arr[0]),
      warnings: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  NoteDetail sse_decode_box_autoadd_note_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_note_detail(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  Category sse_decode_category(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_options = sse_decode_list_category_option(deserializer);
    var var_count = sse_decode_u_32(deserializer);
    return Category(
      path: var_path,
      displayName: var_displayName,
      options: var_options,
      count: var_count,
    );
  }

  @protected
  CategoryOption sse_decode_category_option(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_fullTag = sse_decode_String(deserializer);
    var var_count = sse_decode_u_32(deserializer);
    var var_disabled = sse_decode_bool(deserializer);
    var var_virtualFilter = sse_decode_opt_String(deserializer);
    return CategoryOption(
      name: var_name,
      fullTag: var_fullTag,
      count: var_count,
      disabled: var_disabled,
      virtualFilter: var_virtualFilter,
    );
  }

  @protected
  DetailLine sse_decode_detail_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_urls = sse_decode_list_String(deserializer);
    var var_isBullet = sse_decode_bool(deserializer);
    var var_indentLevel = sse_decode_u_8(deserializer);
    var var_linkedNoteId = sse_decode_opt_box_autoadd_u_32(deserializer);
    return DetailLine(
      text: var_text,
      urls: var_urls,
      isBullet: var_isBullet,
      indentLevel: var_indentLevel,
      linkedNoteId: var_linkedNoteId,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Category> sse_decode_list_category(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Category>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_category(deserializer));
    }
    return ans_;
  }

  @protected
  List<CategoryOption> sse_decode_list_category_option(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CategoryOption>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_category_option(deserializer));
    }
    return ans_;
  }

  @protected
  List<DetailLine> sse_decode_list_detail_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DetailLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_detail_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaItem> sse_decode_list_media_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteSummary> sse_decode_list_note_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SafNote> sse_decode_list_saf_note(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SafNote>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_saf_note(deserializer));
    }
    return ans_;
  }

  @protected
  MediaItem sse_decode_media_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_noteId = sse_decode_u_32(deserializer);
    var var_isVideo = sse_decode_bool(deserializer);
    var var_exists = sse_decode_bool(deserializer);
    var var_mediaCount = sse_decode_u_32(deserializer);
    var var_memoCount = sse_decode_u_32(deserializer);
    var var_relatedCount = sse_decode_u_32(deserializer);
    return MediaItem(
      id: var_id,
      noteId: var_noteId,
      isVideo: var_isVideo,
      exists: var_exists,
      mediaCount: var_mediaCount,
      memoCount: var_memoCount,
      relatedCount: var_relatedCount,
    );
  }

  @protected
  NoteDetail sse_decode_note_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_authorUrl = sse_decode_opt_String(deserializer);
    var var_url = sse_decode_opt_String(deserializer);
    var var_published = sse_decode_opt_String(deserializer);
    var var_created = sse_decode_opt_String(deserializer);
    var var_updated = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_bodyText = sse_decode_String(deserializer);
    var var_memoLines = sse_decode_list_detail_line(deserializer);
    var var_relatedLines = sse_decode_list_detail_line(deserializer);
    var var_media = sse_decode_list_media_item(deserializer);
    return NoteDetail(
      id: var_id,
      path: var_path,
      title: var_title,
      author: var_author,
      authorUrl: var_authorUrl,
      url: var_url,
      published: var_published,
      created: var_created,
      updated: var_updated,
      tags: var_tags,
      bodyText: var_bodyText,
      memoLines: var_memoLines,
      relatedLines: var_relatedLines,
      media: var_media,
    );
  }

  @protected
  NoteSummary sse_decode_note_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_mediaCount = sse_decode_u_32(deserializer);
    var var_videoCount = sse_decode_u_32(deserializer);
    var var_memoCount = sse_decode_u_32(deserializer);
    var var_relatedCount = sse_decode_u_32(deserializer);
    var var_representativeMediaId = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    return NoteSummary(
      id: var_id,
      path: var_path,
      title: var_title,
      mediaCount: var_mediaCount,
      videoCount: var_videoCount,
      memoCount: var_memoCount,
      relatedCount: var_relatedCount,
      representativeMediaId: var_representativeMediaId,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NoteDetail? sse_decode_opt_box_autoadd_note_detail(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_note_detail(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SafNote sse_decode_saf_note(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_modifiedNanos = sse_decode_i_64(deserializer);
    var var_size = sse_decode_i_64(deserializer);
    var var_content = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return SafNote(
      path: var_path,
      modifiedNanos: var_modifiedNanos,
      size: var_size,
      content: var_content,
    );
  }

  @protected
  ScanReport sse_decode_scan_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_notesIndexed = sse_decode_u_32(deserializer);
    var var_warnings = sse_decode_u_32(deserializer);
    return ScanReport(notesIndexed: var_notesIndexed, warnings: var_warnings);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_note_detail(
    NoteDetail self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_note_detail(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_category(Category self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_list_category_option(self.options, serializer);
    sse_encode_u_32(self.count, serializer);
  }

  @protected
  void sse_encode_category_option(
    CategoryOption self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.fullTag, serializer);
    sse_encode_u_32(self.count, serializer);
    sse_encode_bool(self.disabled, serializer);
    sse_encode_opt_String(self.virtualFilter, serializer);
  }

  @protected
  void sse_encode_detail_line(DetailLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_list_String(self.urls, serializer);
    sse_encode_bool(self.isBullet, serializer);
    sse_encode_u_8(self.indentLevel, serializer);
    sse_encode_opt_box_autoadd_u_32(self.linkedNoteId, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_category(List<Category> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_category(item, serializer);
    }
  }

  @protected
  void sse_encode_list_category_option(
    List<CategoryOption> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_category_option(item, serializer);
    }
  }

  @protected
  void sse_encode_list_detail_line(
    List<DetailLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_detail_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_item(
    List<MediaItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_summary(
    List<NoteSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_saf_note(List<SafNote> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_saf_note(item, serializer);
    }
  }

  @protected
  void sse_encode_media_item(MediaItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_u_32(self.noteId, serializer);
    sse_encode_bool(self.isVideo, serializer);
    sse_encode_bool(self.exists, serializer);
    sse_encode_u_32(self.mediaCount, serializer);
    sse_encode_u_32(self.memoCount, serializer);
    sse_encode_u_32(self.relatedCount, serializer);
  }

  @protected
  void sse_encode_note_detail(NoteDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.authorUrl, serializer);
    sse_encode_opt_String(self.url, serializer);
    sse_encode_opt_String(self.published, serializer);
    sse_encode_opt_String(self.created, serializer);
    sse_encode_opt_String(self.updated, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_String(self.bodyText, serializer);
    sse_encode_list_detail_line(self.memoLines, serializer);
    sse_encode_list_detail_line(self.relatedLines, serializer);
    sse_encode_list_media_item(self.media, serializer);
  }

  @protected
  void sse_encode_note_summary(NoteSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_u_32(self.mediaCount, serializer);
    sse_encode_u_32(self.videoCount, serializer);
    sse_encode_u_32(self.memoCount, serializer);
    sse_encode_u_32(self.relatedCount, serializer);
    sse_encode_opt_box_autoadd_u_32(self.representativeMediaId, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_note_detail(
    NoteDetail? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_note_detail(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_saf_note(SafNote self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_i_64(self.modifiedNanos, serializer);
    sse_encode_i_64(self.size, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.content, serializer);
  }

  @protected
  void sse_encode_scan_report(ScanReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.notesIndexed, serializer);
    sse_encode_u_32(self.warnings, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
