// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  NoteDetail dco_decode_box_autoadd_note_detail(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  Category dco_decode_category(dynamic raw);

  @protected
  CategoryOption dco_decode_category_option(dynamic raw);

  @protected
  DetailLine dco_decode_detail_line(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Category> dco_decode_list_category(dynamic raw);

  @protected
  List<CategoryOption> dco_decode_list_category_option(dynamic raw);

  @protected
  List<DetailLine> dco_decode_list_detail_line(dynamic raw);

  @protected
  List<MediaItem> dco_decode_list_media_item(dynamic raw);

  @protected
  List<NoteSummary> dco_decode_list_note_summary(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SafNote> dco_decode_list_saf_note(dynamic raw);

  @protected
  MediaItem dco_decode_media_item(dynamic raw);

  @protected
  NoteDetail dco_decode_note_detail(dynamic raw);

  @protected
  NoteSummary dco_decode_note_summary(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  NoteDetail? dco_decode_opt_box_autoadd_note_detail(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  SafNote dco_decode_saf_note(dynamic raw);

  @protected
  ScanReport dco_decode_scan_report(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  NoteDetail sse_decode_box_autoadd_note_detail(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Category sse_decode_category(SseDeserializer deserializer);

  @protected
  CategoryOption sse_decode_category_option(SseDeserializer deserializer);

  @protected
  DetailLine sse_decode_detail_line(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Category> sse_decode_list_category(SseDeserializer deserializer);

  @protected
  List<CategoryOption> sse_decode_list_category_option(
    SseDeserializer deserializer,
  );

  @protected
  List<DetailLine> sse_decode_list_detail_line(SseDeserializer deserializer);

  @protected
  List<MediaItem> sse_decode_list_media_item(SseDeserializer deserializer);

  @protected
  List<NoteSummary> sse_decode_list_note_summary(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SafNote> sse_decode_list_saf_note(SseDeserializer deserializer);

  @protected
  MediaItem sse_decode_media_item(SseDeserializer deserializer);

  @protected
  NoteDetail sse_decode_note_detail(SseDeserializer deserializer);

  @protected
  NoteSummary sse_decode_note_summary(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  NoteDetail? sse_decode_opt_box_autoadd_note_detail(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  SafNote sse_decode_saf_note(SseDeserializer deserializer);

  @protected
  ScanReport sse_decode_scan_report(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_note_detail(
    NoteDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_category(Category self, SseSerializer serializer);

  @protected
  void sse_encode_category_option(
    CategoryOption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_detail_line(DetailLine self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_category(List<Category> self, SseSerializer serializer);

  @protected
  void sse_encode_list_category_option(
    List<CategoryOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_detail_line(
    List<DetailLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_item(
    List<MediaItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_summary(
    List<NoteSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_saf_note(List<SafNote> self, SseSerializer serializer);

  @protected
  void sse_encode_media_item(MediaItem self, SseSerializer serializer);

  @protected
  void sse_encode_note_detail(NoteDetail self, SseSerializer serializer);

  @protected
  void sse_encode_note_summary(NoteSummary self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_note_detail(
    NoteDetail? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_saf_note(SafNote self, SseSerializer serializer);

  @protected
  void sse_encode_scan_report(ScanReport self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
