[versions]
kotlin = "2.4.0"
compose-multiplatform = "1.12.1"
compose-material3 = "1.9.0"
compose-material3-android = "1.4.0"
agp = "9.4.0"
uniffi-kotlin = "1.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.4.0"
androidx-activity = "1.11.0"
androidx-media3 = "1.8.0"
jna = "5.19.1"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
uniffi-kotlin-multiplatform = { id = "ch.ubique.uniffi.plugin", version.ref = "uniffi-kotlin" }

[libraries]
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-foundation-android = { module = "androidx.compose.foundation:foundation-android", version.ref = "compose-multiplatform" }
compose-material3-android = { module = "androidx.compose.material3:material3-android", version.ref = "compose-material3-android" }
compose-ui-android = { module = "androidx.compose.ui:ui-android", version.ref = "compose-multiplatform" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "androidx-media3" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
