import 'dart:convert';
import 'dart:io';

const _keys = [
  'max_documents',
  'max_depth',
  'max_relative_path_bytes',
  'max_aggregate_path_bytes',
  'max_note_bytes',
  'max_read_batch_notes',
  'max_read_batch_bytes',
  'max_concurrent_note_reads',
  'max_scan_note_bytes',
];

void main(List<String> arguments) {
  final checkOnly = arguments.length == 1 && arguments.single == '--check';
  if (arguments.isNotEmpty && !checkOnly) {
    stderr.writeln('usage: dart tools/generate_saf_limits.dart [--check]');
    exitCode = 2;
    return;
  }

  final root = Directory.current;
  final limits = jsonDecode(
    File('${root.path}/saf-limits.json').readAsStringSync(),
  );
  if (limits is! Map<String, dynamic>) {
    stderr.writeln('saf-limits.json must contain an object.');
    exitCode = 1;
    return;
  }

  final values = <String, int>{};
  for (final key in _keys) {
    final value = limits[key];
    if (value is! int || value <= 0) {
      stderr.writeln('saf-limits.json has an invalid $key value.');
      exitCode = 1;
      return;
    }
    values[key] = value;
  }
  if (limits.keys.toSet().difference(_keys.toSet()).isNotEmpty) {
    stderr.writeln('saf-limits.json contains an unknown limit.');
    exitCode = 1;
    return;
  }
  if (values['max_relative_path_bytes']! >
          values['max_aggregate_path_bytes']! ||
      values['max_note_bytes']! > values['max_read_batch_bytes']! ||
      values['max_note_bytes']! > values['max_scan_note_bytes']! ||
      values['max_read_batch_notes']! > values['max_documents']!) {
    stderr.writeln('saf-limits.json contains inconsistent limits.');
    exitCode = 1;
    return;
  }

  final generated = <String, String>{
    'crates/gallery-core/src/saf_limits.rs': _rust(values),
    'app/lib/platform/saf_limits.g.dart': _dart(values),
    'app/android/app/src/main/kotlin/com/hanaretamae/vault_gallery/SafLimits.kt':
        _kotlin(values),
  };
  var stale = false;
  for (final entry in generated.entries) {
    final file = File('${root.path}/${entry.key}');
    if (checkOnly) {
      if (!file.existsSync() || file.readAsStringSync() != entry.value) {
        stderr.writeln('${entry.key} is stale; run the generator.');
        stale = true;
      }
    } else {
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(entry.value);
    }
  }
  if (stale) exitCode = 1;
}

String _rust(Map<String, int> values) =>
    '''
// Generated by tools/generate_saf_limits.dart; do not edit.
pub const MAX_SAF_DOCUMENTS: usize = ${values['max_documents']};
pub const MAX_SAF_DEPTH: usize = ${values['max_depth']};
pub const MAX_SAF_RELATIVE_PATH_BYTES: usize = ${values['max_relative_path_bytes']};
pub const MAX_SAF_AGGREGATE_PATH_BYTES: usize = ${values['max_aggregate_path_bytes']};
pub const MAX_SAF_NOTE_BYTES: usize = ${values['max_note_bytes']};
pub const MAX_SAF_READ_BATCH_NOTES: usize = ${values['max_read_batch_notes']};
pub const MAX_SAF_READ_BATCH_BYTES: usize = ${values['max_read_batch_bytes']};
pub const MAX_SAF_CONCURRENT_NOTE_READS: usize = ${values['max_concurrent_note_reads']};
pub const MAX_SAF_SCAN_NOTE_BYTES: usize = ${values['max_scan_note_bytes']};
''';

String _dart(Map<String, int> values) =>
    '''
// Generated by tools/generate_saf_limits.dart; do not edit.
abstract final class SafLimits {
  static const maxDocuments = ${values['max_documents']};
  static const maxDepth = ${values['max_depth']};
  static const maxRelativePathBytes = ${values['max_relative_path_bytes']};
  static const maxAggregatePathBytes = ${values['max_aggregate_path_bytes']};
  static const maxNoteBytes = ${values['max_note_bytes']};
  static const maxReadBatchNotes = ${values['max_read_batch_notes']};
  static const maxReadBatchBytes = ${values['max_read_batch_bytes']};
  static const maxConcurrentNoteReads = ${values['max_concurrent_note_reads']};
  static const maxScanNoteBytes = ${values['max_scan_note_bytes']};
}
''';

String _kotlin(Map<String, int> values) =>
    '''
// Generated by tools/generate_saf_limits.dart; do not edit.
internal object SafLimits {
    const val MAX_DOCUMENTS = ${values['max_documents']}
    const val MAX_DEPTH = ${values['max_depth']}
    const val MAX_RELATIVE_PATH_BYTES = ${values['max_relative_path_bytes']}
    const val MAX_AGGREGATE_PATH_BYTES = ${values['max_aggregate_path_bytes']}
    const val MAX_NOTE_BYTES = ${values['max_note_bytes']}
    const val MAX_READ_BATCH_NOTES = ${values['max_read_batch_notes']}
    const val MAX_READ_BATCH_BYTES = ${values['max_read_batch_bytes']}
    const val MAX_CONCURRENT_NOTE_READS = ${values['max_concurrent_note_reads']}
    const val MAX_SCAN_NOTE_BYTES = ${values['max_scan_note_bytes']}
}
''';
