#!/usr/bin/env python3
"""Generate bounded SAF constants for Rust and the platform adapters."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KEYS = (
    "max_documents",
    "max_depth",
    "max_relative_path_bytes",
    "max_aggregate_path_bytes",
    "max_note_bytes",
    "max_read_batch_notes",
    "max_read_batch_bytes",
    "max_concurrent_note_reads",
    "max_scan_note_bytes",
)


def rust(values: dict[str, int]) -> str:
    return f"""// Generated by tools/generate_saf_limits.py; do not edit.
pub const MAX_SAF_DOCUMENTS: usize = {values["max_documents"]};
pub const MAX_SAF_DEPTH: usize = {values["max_depth"]};
pub const MAX_SAF_RELATIVE_PATH_BYTES: usize = {values["max_relative_path_bytes"]};
pub const MAX_SAF_AGGREGATE_PATH_BYTES: usize = {values["max_aggregate_path_bytes"]};
pub const MAX_SAF_NOTE_BYTES: usize = {values["max_note_bytes"]};
pub const MAX_SAF_READ_BATCH_NOTES: usize = {values["max_read_batch_notes"]};
pub const MAX_SAF_READ_BATCH_BYTES: usize = {values["max_read_batch_bytes"]};
pub const MAX_SAF_CONCURRENT_NOTE_READS: usize = {values["max_concurrent_note_reads"]};
pub const MAX_SAF_SCAN_NOTE_BYTES: usize = {values["max_scan_note_bytes"]};
"""


def android_kotlin(values: dict[str, int]) -> str:
    return f"""// Generated by tools/generate_saf_limits.py; do not edit.
package com.hanaretamae.kaede.core.rust

internal object AndroidSafLimits {{
    const val MAX_CONCURRENT_NOTE_READS = {values["max_concurrent_note_reads"]}
}}
"""


def outputs(values: dict[str, int]) -> dict[str, str]:
    return {
        "crates/gallery-core/src/saf_limits.rs": rust(values),
        "kotlin/core/rust/src/androidMain/kotlin/com/hanaretamae/kaede/core/rust/AndroidSafLimits.kt": android_kotlin(
            values
        ),
    }


def load_values() -> dict[str, int]:
    raw = json.loads((ROOT / "saf-limits.json").read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError("saf-limits.json must contain an object")
    if set(raw) != set(KEYS):
        raise ValueError("saf-limits.json has missing or unknown limits")
    values: dict[str, int] = {}
    for key in KEYS:
        value = raw[key]
        if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
            raise ValueError(f"saf-limits.json has an invalid {key} value")
        values[key] = value
    if (
        values["max_relative_path_bytes"] > values["max_aggregate_path_bytes"]
        or values["max_note_bytes"] > values["max_read_batch_bytes"]
        or values["max_note_bytes"] > values["max_scan_note_bytes"]
        or values["max_read_batch_notes"] > values["max_documents"]
    ):
        raise ValueError("saf-limits.json contains inconsistent limits")
    return values


def main() -> int:
    arguments = sys.argv[1:]
    if arguments not in ([], ["--check"]):
        print("usage: python3 tools/generate_saf_limits.py [--check]", file=sys.stderr)
        return 2
    check_only = arguments == ["--check"]
    generated = outputs(load_values())
    stale = False
    for relative, contents in generated.items():
        path = ROOT / relative
        if check_only:
            if not path.is_file() or path.read_text(encoding="utf-8") != contents:
                print(f"{relative} is stale; run the generator.", file=sys.stderr)
                stale = True
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            temporary = path.with_suffix(path.suffix + ".tmp")
            try:
                temporary.write_text(contents, encoding="utf-8", newline="\n")
                temporary.replace(path)
            finally:
                temporary.unlink(missing_ok=True)
    return 1 if stale else 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
